### ISSUE TITLE
Question, does this provide both encrypting and decrypting?

### ISSUE THREAD

**Issue by VaasKahnGrim** [danielga/gm_crypt#6]
You already know I'm working on a module for use with my stuff(given you've helped with advice and finding out whats wrong with my code and such)

I was looking for a working example of both SHA512 and AES, both for doing and undoing thise on a string I feed it, that was already designed to be used for gmod. I found 3 so far, 2 versions of gm_hash and then this. the other 2 didn't offer what I needed but this one looks more promising and I was wondering if this had those capabilities?

**Comment by danielga** [comment]
Both SHA512 and AES (CTR mode) are supported. As for examples, I don't have any. I should probably spend a few minutes writing a simple documentation for the API of the module to help.
